### ISSUE TITLE
Проблемы с Non-ASCII character при запуске под Win7

### ISSUE THREAD

**Issue by dkx86** [sullome/charfly#14]
При попытке запуска под Win7 питон ругается на кириллицу в скриптах.

```
PS D:\DevSpace\charfly\charfly> python.exe .\main.py
Traceback (most recent call last):
  File ".\main.py", line 2, in <module>
    from rollingdice.fudge import fudge
  File "D:\DevSpace\charfly\charfly\rollingdice\fudge.py", line 6
SyntaxError: Non-ASCII character '\xd1' in file D:\DevSpace\charfly\charfly\rollingdice\fudge.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

```
PS D:\DevSpace\charfly\charfly> python.exe .\qt5.py
  File ".\qt5.py", line 39
SyntaxError: Non-ASCII character '\xd0' in file .\qt5.py on line 39, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

Python 2.7.1

**Comment by sullome** [comment]
А с Python 3 и выше?
